### ISSUE TITLE
Invalid template file

### ISSUE THREAD

**Issue by steros** [PAYONE-GmbH/magento-2#160] opened 2018-03-20 10:37 UTC
Since switching from Magento 1.x to 2.x I get these errors often. Those are the only errors in my magento log usually.
Currently I'm on 2.1.11 with the plugin being version 2.1.0.
I'm using a custom template inherited from a custom base template.

> [2018-03-12 11:29:40] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_paypal' [] []
> [2018-03-12 11:29:40] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_obt_sofortueberweisung' [] []
> [2018-03-12 11:29:40] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_creditcard' [] []
> [2018-03-12 11:29:40] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_invoice' [] []
> [2018-03-12 11:30:29] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_paypal' [] []
> [2018-03-12 11:30:29] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_obt_sofortueberweisung' [] []
> [2018-03-12 11:30:29] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_creditcard' [] []
> [2018-03-12 11:30:29] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_invoice' [] []
> [2018-03-12 11:31:05] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_paypal' [] []
> [2018-03-12 11:31:05] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_obt_sofortueberweisung' [] []
> [2018-03-12 11:31:05] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_creditcard' [] []
> [2018-03-12 11:31:05] main.CRITICAL: Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_invoice' [] []

**Comment by fjbender** [comment] 2018-03-20 13:43
I have never encountered this error. Maybe just copying view/frontend/templates/form/base.phtml into your template solves the issue? It seems like the other templates are not affected (i.e. credit card processing works)?

**Comment by steros** [comment] 2018-03-20 14:21
All payment methods I use, and who are mentioned in the errors, work as expected. I'm not even sure something is "wrong" except the error popping up.
Also other payone templates are loading like for credit card or debit confirmation.

**Comment by fjbender** [comment] 2018-04-06 11:43
This is a duplicate of #158

**Closed by fjbender** 2018-04-06 11:43 UTC
